project:
  type: website

website:
  title: "Peter Bachman"
  site-url: https://peterjbachman.lol
  repo-url: https://github.com/peterjbachman/personalWebsite
  description: "Personal Musings and How-Tos"
  image: profile.webp
  image-alt: "Peter Bachman's Personal Website"
  search: false
  bread-crumbs: false
  navbar:
    # logo: logo.svg
    left:
      - text: "About"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
    collapse: false
  page-footer: 
    left: "Copyright 2024, Peter Bachman" 
    center: 
      - icon: github
        href: https://github.com/peterjbachman
      - icon: linkedin
        href: https://www.linkedin.com/in/peterjbachman
      - icon: mastodon
        href: https://mastodon.online/@peterjbachman
      - icon: rss
        href: blog.xml
  open-graph: true
format:
  html:
    theme:
      # light:
        - litera
        - styles_light.scss
      # dark:
      #   - litera
      #   - styles_dark.scss
    fontsize: 1.15em
    css: styles.css
    # mainfont: Elstob
    # monofont: Berkeley
