project:
  type: website

website:
  title: "Peter Bachman"
  site-url: https://peterjbachman.lol
  description: "Personal Musings and How-Tos"
  navbar:
    left:
      - text: "Blog"
        href: blog.qmd
    right:
      - text: "About"
        href: index.qmd
  page-footer: 
    left: "Copyright 2024, Peter Bachman" 
    center: 
      - icon: github
        href: https://github.com/peterjbachman
      - icon: mastodon
        href: https://mastodon.online/@peterjbachman
      - icon: rss
        href: blog.xml
format:
  html:
    theme:
      light:
        - litera
        - styles_light.scss
      dark:
        - litera
        - styles_dark.scss
    # fontsize: 1.15em
    css: styles.css
    # mainfont: Elstob
    # monofont: Berkeley
