baseURL = "/"
languageCode = "en-us"
title = "Peter Bachman"
theme = "archie"
copyright = "© Peter Bachman"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[params]
	mode="auto"
	featherIconsCDN=true
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/peterjbachman"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/peterjbachman"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:peter.j.bachman@gmail.com"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
