baseURL = "https://peterjbachman.rbind.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Peter Bachman"
theme = "hugo-classic"
summarylength = 0
enableEmoji = true
enableRobotsTXT = false

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Research"
  weight = 300
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Teaching"
  weight = 400
  identifier = "Teaching"
  url = "/teaching/"

  [[menu.main]]
  name = "CV"
  weight = 500
  identifier = "cv"
  url = "/files/cv.pdf"

  [[menu.main]]
  name = "Blog"
  weight = 600
  identifier = "blog"
  url = "/post/"

[params]
custom_css = ["css/style.css"]
description = "A simple, minimal blog for those who love text."
footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Keybase](https://keybase.io/goodroot)"
