baseURL = "https://peterjbachman.rbind.io"
title = "Peter Bachman"
theme = "hugo-theme-m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "files/bachman_cv_2021.pdf"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[params]
  author = "Peter Bachman"
  description = "Undergraduate at Utah State University. Political Science and Statistics. I'm interested in the effects communication has on political institutions and elections."
  avatar = "images/avatar.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/peterjbachman"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/peterjbachman"
  [[params.social]]
    name = "mail"
    url = "mailto:peter.j.bachman@gmail.com"

  # Kiss Theme
  [params.style]
    darkestColor = "#202020"
    darkColor = "#202020"
    primaryColor = "#37A4ED"
    lightColor = "#c9c9c9"
    lightestColor = "#c9c9c9"
