baseURL: https://peterjbachman.rbind.io
languageCode: en-us
defaultContentLanguage: en
title: Peter Bachman
theme: cupper-hugo-theme
enableGitInfo: true
googleAnalytics: G-CX16GW6PZY

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Peter Bachman's Personal Website
  homeMetaContent: Peter Bachman's Personal Website
  footer: "[Twitter](https://twitter.com/peterjbachman/) | [Github](https://github.com/peterjbachman) | [Email](mailto:peter.j.bachman@gmail.com) | [Spotify](https://open.spotify.com/user/x5xyifk4f697kabe2mm1u95p5?si=pFRMGhfAQzKed1worpmy2w)"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: true
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: CV
      url: /files/cv.pdf
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
