baseurl = "https://peterjbachman.rbind.io"
languageCode = "en-us"
title = "Peter Bachman"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
    
[[menu.main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 5

[params]
    description = ""
    avatar = "images/avatar.png"
    footer = "&copy; Peter Bachman 2020 | [Github](https://github.com/peterjbachman) | [Twitter](https://twitter.com/peterjbachman)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
