baseURL = "https://peterjbachman.rbind.io"
title = "Peter Bachman"
theme = "hugo-theme-m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "files/cv.pdf"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

[params]
  author = "Peter Bachman"
  avatar = "images/avatar.png"
  description = "Undergraduate at Utah State University. Political Science. I'm interested in the effects communication has on political institutions and elections."
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/peterjbachman"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/peterjbachman"
  [[params.social]]
    name = "mail"
    url = "mailto:peter.j.bachman@gmail.com"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  [params.style]
    darkestColor = "#3d3d3d"
    darkColor = "#333333"
    primaryColor = "#999999"
    lightColor = "#fff"
    lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
